spring.application.name=Money_Manager
server.port=8081
server.servlet.context-path=/api/v1.0

# MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/money_manager?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=ss@21


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#For MySQL
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


brevo.api.key=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
brevo.sender.email=sudipsamanta0010@gmail.com
brevo.sender.name=Money_manager
spring.jpa.open-in-view=false

#JWT
jwt.secret=6d1e7f4c8d1a9e3f6b2c7d8a1f9e4b6c3d8e1a7b5f2c9d4e6a8b1c3d5f7e9a2


# Frontend
money.manager.frontend.url=http://localhost:5173

#Backend
money.manager.backend.url=http://localhost:8081

#import </> application-prod.properties
spring.profiles.active=prod