
# Postgresql
spring.datasource.url=jdbc:postgresql://dpg-d98jsgernols73feitq0-a.singapore-postgres.render.com:5432/money_manager_jcqv
spring.datasource.username=money_manager_jcqv_user
spring.datasource.password=WPfTAGgIM1QY4PM9HQCD0zIROTL8X0CK

spring.datasource.driver-class-name=org.postgresql.Driver


# JPA
spring.jpa.hibernate.ddl-auto=update
