spring.application.name=Money_Manager
server.port=8081
server.servlet.context-path=/api/v1.0

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


brevo.api.key=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
brevo.sender.email=sudipsamanta0010@gmail.com
brevo.sender.name=Money_manager
spring.jpa.open-in-view=false

#JWT
jwt.secret=${JWT_SECRET}


# Frontend
money.manager.frontend.url=http://localhost:5173

#Backend
money.manager.backend.url=http://localhost:8081

#import </> application-prod.properties
spring.profiles.active=prod
